### ISSUE TITLE
RuntimeException: No ResponseFactoryInterface detected 

### ISSUE THREAD

**Issue by mueller-ma** [humhub/humhub-modules-linkpreview#44]
When entering a link in a text box, a loading progress shows up for a few seconds until it vanishes. No preview is generated.
In browser dev tools I can see a POST to `<humhub>/linkpreview/index/fetch` with http code 500 and response `{"error":true,"message":"Es ist ein interner Fehler aufgetreten."}` (Humhub is set to German).

In the log there's the following error:

````
RuntimeException: No ResponseFactoryInterface detected in /var/www/localhost/htdocs/protected/modules/linkpreview/vendor/embed/embed/src/Http/FactoryDiscovery.php:52
Stack trace:
#0 /var/www/localhost/htdocs/protected/modules/linkpreview/vendor/embed/embed/src/Http/CurlClient.php(21): Embed\Http\FactoryDiscovery::getResponseFactory()
#1 /var/www/localhost/htdocs/protected/modules/linkpreview/vendor/embed/embed/src/Http/Crawler.php(25): Embed\Http\CurlClient->__construct()
#2 /var/www/localhost/htdocs/protected/modules/linkpreview/vendor/embed/embed/src/Embed.php(17): Embed\Http\Crawler->__construct()
#3 /var/www/localhost/htdocs/protected/modules/linkpreview/controllers/IndexController.php(44): Embed\Embed->__construct()
#4 [internal function]: humhub\modules\linkpreview\controllers\IndexController->actionFetch()
#5 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#6 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#7 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#8 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#9 /var/www/localhost/htdocs/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#10 /var/www/localhost/htdocs/index.php(28): yii\base\Application->run()
#11 {main} 
````

- HumHub Professional Edition 1.16.1
- PHP - Version - 8.1.27
- All PHP extensions are installed accoring to `/admin/information/prerequisites`
- ![grafik](https://github.com/user-attachments/assets/553e4330-872f-4b74-930f-afa0e21ebd20)

**Comment by luke-** [comment]
@gevorgmansuryan Thanks for the fix!

@mueller-ma Should be fixeed in 2.0.5
