### ISSUE TITLE
The module is not compatible with 1.17 any more

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub-modules-linkpreview#45]
`AbstractRichText::$record` has been removed on HumHub 1.17:
[(https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/widgets/richtext/AbstractRichText.php#L150)](https://github.com/humhub/humhub/commit/fa82ce32b9e5903f42212ef4ca81aab7a5c7f451)

But it is still used here: https://github.com/humhub/linkpreview/blob/master/Events.php#L80

Error log:
```
yii\base\UnknownPropertyException: Getting unknown property: humhub\modules\content\widgets\richtext\ProsemirrorRichText::record in /var/www/dev/protected/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /var/www/dev/protected/modules_paid/linkpreview/Events.php(80): yii\base\Component->__get()
#1 [internal function]: humhub\modules\linkpreview\Events::onRichTextOutput()
#2 /var/www/dev/protected/vendor/yiisoft/yii2/base/Event.php(312): call_user_func()
#3 /var/www/dev/protected/vendor/yiisoft/yii2/base/Component.php(654): yii\base\Event::trigger()
#4 /var/www/dev/protected/humhub/modules/content/widgets/richtext/ProsemirrorRichText.php(155): yii\base\Component->trigger()
#5 /var/www/dev/protected/humhub/components/Widget.php(62): humhub\modules\content\widgets\richtext\ProsemirrorRichText->run()
#6 [internal function]: humhub\components\Widget::widget()
#7 /var/www/dev/protected/humhub/modules/content/widgets/richtext/RichText.php(57): call_user_func()
#8 /var/www/dev/protected/humhub/modules/content/widgets/richtext/AbstractRichText.php(290): humhub\modules\content\widgets\richtext\RichText::widget()
#9 /var/www/dev/protected/modules/legal/widgets/views/content.php(21): humhub\modules\content\widgets\richtext\AbstractRichText::output()
#10 /var/www/dev/protected/vendor/yiisoft/yii2/base/View.php(348): require('...')
#11 /var/www/dev/protected/vendor/yiisoft/yii2/base/View.php(258): yii\base\View->renderPhpFile()
#12 /var/www/dev/protected/vendor/yiisoft/yii2/base/View.php(157): yii\base\View->renderFile()
#13 /var/www/dev/protected/vendor/yiisoft/yii2/base/Widget.php(249): yii\base\View->render()
#14 /var/www/dev/protected/modules/legal/widgets/Content.php(40): yii\base\Widget->render()
#15 /var/www/dev/protected/humhub/components/Widget.php(62): humhub\modules\legal\widgets\Content->run()
#16 /var/www/dev/protected/modules/legal/widgets/views/cookies.php(14): humhub\components\Widget::widget()
#17 /var/www/dev/protected/vendor/yiisoft/yii2/base/View.php(348): require('...')
#18 /var/www/dev/protected/vendor/yiisoft/yii2/base/View.php(258): yii\base\View->renderPhpFile()
#19 /var/www/dev/protected/vendor/yiisoft/yii2/base/View.php(157): yii\base\View->renderFile()
#20 /var/www/dev/protected/vendor/yiisoft/yii2/base/Widget.php(249): yii\base\View->render()
#21 /var/www/dev/protected/modules/legal/widgets/CookieNote.php(27): yii\base\Widget->render()
#22 /var/www/dev/protected/humhub/components/Widget.php(62): humhub\modules\legal\widgets\CookieNote->run()
#23 /var/www/dev/protected/humhub/widgets/BaseStack.php(87): humhub\components\Widget::widget()
#24 /var/www/dev/protected/humhub/components/Widget.php(62): humhub\widgets\BaseStack->run()
#25 /var/www/dev/protected/humhub/modules/ui/view/components/View.php(498): humhub\components\Widget::widget()
#26 /var/www/dev/protected/modules_cuzy/clean-theme/themes/Clean/views/humhub/layouts/main.php(86): humhub\modules\ui\view\components\View->endBody()
#27 /var/www/dev/protected/vendor/yiisoft/yii2/base/View.php(348): require('...')
#28 /var/www/dev/protected/vendor/yiisoft/yii2/base/View.php(258): yii\base\View->renderPhpFile()
#29 /var/www/dev/protected/humhub/components/Controller.php(155): yii\base\View->renderFile()
#30 /var/www/dev/protected/vendor/yiisoft/yii2/base/Controller.php(408): humhub\components\Controller->renderContent()
#31 /var/www/dev/protected/humhub/modules/space/controllers/SpaceController.php(102): yii\base\Controller->render()
#32 [internal function]: humhub\modules\space\controllers\SpaceController->actionHome()
#33 /var/www/dev/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#34 /var/www/dev/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#35 /var/www/dev/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#36 /var/www/dev/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#37 /var/www/dev/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#38 /var/www/dev/index.php(33): yii\base\Application->run()
#39 {main}
```

**Comment by gevorgmansuryan** [comment]
@luke- LinkPreview has functionality to add link previews for RichTextOutput, it worked based on (removed https://github.com/humhub/humhub/pull/7211) `$record` property. Do we need this functionality, bring back `$record` or remove this functionality too?

**Comment by luke-** [comment]
@yurabakhtin Didn't we recently removed something here?

**Comment by yurabakhtin** [comment]
> @yurabakhtin Didn't we recently removed something here?

@luke- Yes, we deleted the `$record` property as @gevorgmansuryan mentioned above.
We discussed it [here](https://github.com/humhub/translator/issues/52#issuecomment-2334600960).
It seems it was a mistake to remove the property because at least this module uses it.
I also find the property is used in the module `legal` [here](https://github.com/humhub/legal/blob/master/Events.php#L259).
I think we must revert all changes from the PR https://github.com/humhub/humhub/pull/7211.

**Comment by luke-** [comment]
@yurabakhtin Can you explain the use case for the property from this two modules?

**Comment by yurabakhtin** [comment]
@luke- 

> Can you explain the use case for the property from this two modules?

1. [linkpreview](https://github.com/humhub/linkpreview) - this module requires the property `record` for the widget [Viewer](https://github.com/humhub/linkpreview/blob/master/widgets/Viewer.php#L44) in order to get a record from table `linkpreview`:

```php
LinkPreview::findOne(['class' => $this->record->className(), 'pk' => $this->record->getPrimaryKey()]);
```

2. [legal](https://github.com/humhub/legal) - this module applies the widget `humhub\modules\legal\widgets\Content` only when the `$record` is Post or Comment, the code is [here](https://github.com/humhub/legal/blob/master/Events.php#L263).

**Comment by luke-** [comment]
@yurabakhtin Thanks. I've created an issue for it here: https://github.com/humhub/humhub-internal/issues/424
